classDiagram
    class MakeFacturaController {
        -SendInvoiceUseCase sendInvoiceUseCase
        -GenerateInvoicePdfUseCase generateInvoicePdfUseCase
        +makePdf(Long clienteMovimientoId) ResponseEntity~Resource~
        +send(Long clienteMovimientoId, String email) ResponseEntity~String~
    }

    class SendInvoiceUseCase {
        <<interface>>
        +sendInvoice(Long clienteMovimientoId, String email) String
    }

    class GenerateInvoicePdfUseCase {
        <<interface>>
        +generatePdf(Long clienteMovimientoId) Resource
    }

    class SendInvoiceUseCaseImpl {
        -InvoiceDataRepository invoiceDataRepository
        -GenerateInvoicePdfUseCase generateInvoicePdfUseCase
        -JavaMailSender javaMailSender
        +sendInvoice(Long clienteMovimientoId, String email) String
    }

    class GenerateInvoicePdfUseCaseImpl {
        -InvoiceDataRepository invoiceDataRepository
        -FacturaPdfService facturaPdfService
        +generatePdf(Long clienteMovimientoId) Resource
    }

    class InvoiceDataRepository {
        <<interface>>
        +findByClienteMovimientoId(Long clienteMovimientoId) InvoiceData
    }

    class InvoiceDataRepositoryImpl {
        -InvoiceDataClient invoiceDataClient
        +findByClienteMovimientoId(Long clienteMovimientoId) InvoiceData
    }

    class FacturaPdfService {
        -Environment environment
        -InvoiceDataService invoiceDataService
        +generatePdf(Long clienteMovimientoId, InvoiceData invoiceData) String
    }

    class InvoiceDataService {
        -InvoiceDataClient invoiceDataClient
        +getInvoiceDataByClienteMovimientoId(Long clienteMovimientoId) InvoiceData
    }

    MakeFacturaController --> SendInvoiceUseCase
    MakeFacturaController --> GenerateInvoicePdfUseCase
    SendInvoiceUseCase <|.. SendInvoiceUseCaseImpl
    GenerateInvoicePdfUseCase <|.. GenerateInvoicePdfUseCaseImpl
    SendInvoiceUseCaseImpl --> InvoiceDataRepository
    GenerateInvoicePdfUseCaseImpl --> InvoiceDataRepository
    GenerateInvoicePdfUseCaseImpl --> FacturaPdfService
    InvoiceDataRepository <|.. InvoiceDataRepositoryImpl
    InvoiceDataRepositoryImpl --> InvoiceDataClient
    FacturaPdfService --> InvoiceDataService
    InvoiceDataService --> InvoiceDataClient

    interface InvoiceDataClient {
        +getInvoiceDataByClienteMovimientoId(Long clienteMovimientoId) InvoiceData
    }

    class InvoiceData {
        -ClienteMovimiento clienteMovimiento
        -RegistroCae registroCae
        -ClienteMovimiento clienteMovimientoAsociado
    }

    class Comprobante {
        <<record>>
        +String letraComprobante
        +Byte contado
        +ComprobanteAfip comprobanteAfip
    }

    class ComprobanteAfip {
        <<record>>
        +Integer comprobanteAfipId
        +String label
    }

    class Moneda {
        <<record>>
        +String simbolo
    }
