classDiagram
    class MakeFacturaController {
        -MakeFacturaService service
        -FacturaPdfService facturaPdfService
        +makePdf(Long clienteMovimientoId) ResponseEntity~Resource~
        +send(Long clienteMovimientoId, String email) ResponseEntity~String~
    }

    class MakeFacturaService {
        -FacturaPdfService facturaPdfService
        -InvoiceDataClient invoiceDataClient
        -JavaMailSender javaMailSender
        +send(Long clienteMovimientoId, String email) String
    }

    class FacturaPdfService {
        -Environment environment
        -InvoiceDataService invoiceDataService
        +generatePdf(Long clienteMovimientoId, InvoiceData invoiceData) String
    }

    class InvoiceDataService {
        -InvoiceDataClient invoiceDataClient
        +getInvoiceDataByClienteMovimientoId(Long clienteMovimientoId) InvoiceData
    }

    MakeFacturaController --> MakeFacturaService
    MakeFacturaController --> FacturaPdfService
    MakeFacturaService --> FacturaPdfService
    MakeFacturaService --> InvoiceDataClient
    FacturaPdfService --> InvoiceDataService
    InvoiceDataService --> InvoiceDataClient

    interface InvoiceDataClient {
        +getInvoiceDataByClienteMovimientoId(Long clienteMovimientoId) InvoiceData
    }

    class InvoiceData {
        -ClienteMovimiento clienteMovimiento
        -RegistroCae registroCae
        -ClienteMovimiento clienteMovimientoAsociado
    }
